name: nlp_literatura_cientifica
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9
  - jupyter
  - numpy
  - pandas
  - spacy
  - scikit-learn
  - streamlit
  - huggingface_hub